### ISSUE TITLE
Change boot disk size

### ISSUE THREAD

**Issue by zallaevan** [jshcmpbll/Cloud-Mac-KVM#33]
First of all, I want to congratulate you on your great work with this. Absolutely brilliant!
However, when I want to install the OS, the boot disk is about 10 GB so there isn't enough room to install macOS (I suppose it is around 20-30 GBs). So, I'd like to have in a new update an option to change the disk size, or you may help me with it tinkering around the actual config. Thanks in advance.

Edit:
I have seen in the variables file that you can change the size of the disk, although after changing it the boot disk still displays 10GB. Also, I've seen that after installing the System into an uninitialized disk of about 180GB that happened to be there, it get's stuck on %25 percent. I dunno how to continue. Any help is appreciated.

**Comment by jshcmpbll** [comment]
@zallaevan

Totally valid point. When setting this project up I had made the default size much smaller to cut down on costs (I was rapidly spinning up and down the system and wasn't going through the actual install process). Being that the project is stable I should switch the default disk to an appropriate size.

I'm going to redeploy this (haven't done it in some time) and see if I hit any issues. 

Did you rerun `terraform apply` after changing the disk size?

**Comment by zallaevan** [comment]
Thank you for your fast reply. I have changed the 10GB variable in the variable.tf, but no luck so far. The macOS boot disk still shows ~5GB (I think). I recreated all the steps with a fresh GCP acc, but no luck neither (after changing the variables file again). So, I think that applying the `terraform apply` command, in this case, is unnecessary. If you need some screenshots or something please tell me.
P.D.: every time I install it to the unknown drive with 180GB free space, it gets stuck on 17 minutes left. I can't install it to any other disk, even if I connect an external HDD (or maybe I haven't mounted it, so that's why it doesn't detect it, but I dunno how to mount it... so noob am I). However, it seems that the system isn't halted cuz I can connect to the VPS via VNC, but the mouse nor the kb responds to any action.

**Comment by jshcmpbll** [comment]
Sorry I forgot to send an update once I finished last night. It looks that the disk size parameter wasnt actually populated in the disk resource creation. Im working on a PR to fix that and a couple other things.

https://github.com/jshcmpbll/Cloud-Mac-KVM/pull/36

**Comment by zallaevan** [comment]
Okay, I have seen the comments and also I've answered them, and added a couple more.

BTW, happy new year!

**Comment by jshcmpbll** [comment]
Happy new year! @zallaevan i added comments to your comments but I tested it and you should be good to rock.

**Comment by jshcmpbll** [comment]
@zallaevan Let me know if you are still having issues bit I think you should be all set. I just spun up a VM with 4 cores and it was okay but I think increasing that to 8+ would be a much better experience. Feel free to adjust as needed on your end in the variables.tf file.

**Comment by zallaevan** [comment]
Yeah, I've seen the comments. I'm trying the config right now, as I haven't had any spare time during the day. I'll let u catch up with any news.

**Comment by jshcmpbll** [comment]
No worries, just wanted to check in. Happy new year!

**Comment by zallaevan** [comment]
Okay, I've installed macOS, but I dunno why it gets frozen after installation. Also, after forced reboot, I can't connect to vnc anymore, and I dunno how to re-execute "the script" so to restart vnc sever.

**Comment by jshcmpbll** [comment]
```MY_OPTIONS="+pcid,+ssse3,+sse4.2,+popcnt,+avx,+aes,+xsave,+xsaveopt,check"
  MEM=$(expr $(free -mt | grep Total | awk '{print $2}') - 2048)
  CPU=$(nproc --all)
  PASSWORD=password

  printf "change vnc password\n%s\n" ${PASSWORD} | qemu-system-x86_64 -enable-kvm -m $MEM -cpu Penryn,kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on,$MY_OPTIONS\
    -machine q35 \
    -smp $CPU,cores=$CPU \
    -usb -device usb-kbd -device usb-tablet \
    -device isa-applesmc,osk="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"\
    -drive if=pflash,format=raw,readonly,file=/OSX-KVM/OVMF_CODE.fd \
    -drive if=pflash,format=raw,file=/OSX-KVM/OVMF_VARS-1024x768.fd \
    -smbios type=2 \
    -device ich9-intel-hda -device hda-duplex \
    -device ich9-ahci,id=sata \
    -drive id=OpenCore,if=none,snapshot=on,format=qcow2,file=/OSX-KVM/OpenCore-Catalina/OpenCore.qcow2 -device ide-hd,bus=sata.1,drive=OpenCore\
    -drive id=MacHDD,if=none,file=/${USERNAME},format=qcow2 -device ide-hd,bus=sata.3,drive=MacHDD \
    -netdev user,id=net0 -device e1000-82545em,netdev=net0,id=net0,mac=52:54:00:c9:18:27 \
    -monitor stdio -vnc :0,password```
    
    As the root user - `sudo -i` you should be able to run that above a restart the VM.
    
    Sounds odd that it keeps freezing though.. What VNC service are you using? Im using TigerVNC and it seems pretty reliable, my try switching to that and see if its acting better.

**Comment by zallaevan** [comment]
Okay, it seems to be the last part of the init scrip... I'm using RealVNC as it is the default one in RasPi. (I'm not using raspi, but since I used it from the first time I haven't bothered to switch to tigervnc). I've reinstalled, and I'm just finishing the installation right now.

**Comment by jshcmpbll** [comment]
Yeah, RealVNC should be fine. Feel free to ping me on discord and we can just on a call to debug if you want - Jsh#3038

Hopefully the install you are running works though!

**Comment by zallaevan** [comment]
It's a pity... It seems that no luck this time neither! Discord tells me that you can't receive friend requests, so I think it's better if you add me - zallaevan#0322

**Comment by zallaevan** [comment]
Okay, after tinkering around and with the guidance of @jshcmpbll, we've figured out what was happening:
- There were some errors with some variables, but they were corrected quickly.
- After installation, the screen froze, but to solve it we just needed to restart the qemu service with the last part of the initial script:
> ```
>   MEM=$(expr $(free -mt | grep Total | awk '{print $2}') - 2048)
>   CPU=$(nproc --all)
>   PASSWORD=password
> 
>   printf "change vnc password\n%s\n" ${PASSWORD} | qemu-system-x86_64 -enable-kvm -m $MEM -cpu Penryn,kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on,$MY_OPTIONS\
>     -machine q35 \
>     -smp $CPU,cores=$CPU \
>     -usb -device usb-kbd -device usb-tablet \
>     -device isa-applesmc,osk="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"\
>     -drive if=pflash,format=raw,readonly,file=/OSX-KVM/OVMF_CODE.fd \
>     -drive if=pflash,format=raw,file=/OSX-KVM/OVMF_VARS-1024x768.fd \
>     -smbios type=2 \
>     -device ich9-intel-hda -device hda-duplex \
>     -device ich9-ahci,id=sata \
>     -drive id=OpenCore,if=none,snapshot=on,format=qcow2,file=/OSX-KVM/OpenCore-Catalina/OpenCore.qcow2 -device ide-hd,bus=sata.1,drive=OpenCore\
>     -drive id=MacHDD,if=none,file=/user1,format=qcow2 -device ide-hd,bus=sata.3,drive=MacHDD \
>     -netdev user,id=net0 -device e1000-82545em,netdev=net0,id=net0,mac=52:54:00:c9:18:27 \
>     -monitor stdio -vnc :0,password
> ```

Now everything seems to work flawlessly. Thank you again for your support, @jshcmpbll!
