### ISSUE TITLE
Does it has to be Terraform CLI v0.11.12? 

### ISSUE THREAD

**Issue by mobilelifeful** [jshcmpbll/Cloud-Mac-KVM#40]
install Terraform from brew, which has the version 
```
Terraform v1.1.7
on darwin_amd64
```
and updated the version from 
`main.tf `
but can't get it to work.

after run:
terraform init 
give

 Warning: Quoted references are deprecated
│ 
│   on networks.tf line 9, in resource "google_compute_subnetwork" "subnet":
│    9:   depends_on    = ["google_compute_network.network"]
│ 
│ In this context, references are expected literally rather than in quotes. Terraform 0.11 and earlier required quotes, but quoted references are now
│ deprecated and will be removed in a future version of Terraform. Remove the quotes surrounding this reference to silence this warning.
│ 
│ (and 2 more similar warnings elsewhere)
╵

╷
│ Error: Unsupported argument
│ 
│   on main.tf line 9, in terraform:
│    9:   required_vesrion = "1.1.7"
│ 
│ An argument named "required_vesrion" is not expected here. Did you mean "required_version"?
╵

╷
│ Error: Invalid output name
│ 
│   on outputs.tf line 1, in output "instance ip":
│    1: output "instance ip" {
│ 
│ A name must start with a letter or underscore and may contain only letters, digits, underscores, and dashes.
╵

╷
│ Error: Invalid quoted type constraints
│ 
│   on variables.tf line 58, in variable "vnc_password":
│   58:   type = "list"
│ 
│ Terraform 0.11 and earlier required type constraints to be given in quotes, but that form is now deprecated and will be removed in a future version of
│ Terraform. Remove the quotes around "list" and write list(string) instead to explicitly indicate that the list elements are strings.
╵

Please advice.

**Comment by jshcmpbll** [comment]
Unfortunately yes. For this project I set a requirement for that specific version. You can see that set [here](https://github.com/jshcmpbll/Cloud-Mac-KVM/blob/6f5f53b67567d3991b84ab028943d1e6ee03e400/GCP/terraform/main.tf#L9)

Projects should use pinned versions of terraform, its just a good practice since features in HCL can change. You could try changing that version and see how it goes but I wold recommend just using the tool [tfenv](https://github.com/tfutils/tfenv) to change the version of terraform in your local path.

```bash
brew install tfenv
tfenv install 0.11.12
tfenv use 0.11.12
```

**Comment by mobilelifeful** [comment]
Thank you for the quick response, 
This error may not cause by this repo, but please share any hit if,


```
(base) x@xnoMacBook-Pro terraform % tfenv install 0.11.12
Installing Terraform v0.11.12
Downloading release tarball from https://releases.hashicorp.com/terraform/0.11.12/terraform_0.11.12_darwin_amd64.zip
######################################################################################################################################################### 100.0%
Downloading SHA hash file from https://releases.hashicorp.com/terraform/0.11.12/terraform_0.11.12_SHA256SUMS
No keybase install found, skipping OpenPGP signature verification
Archive:  /var/folders/t4/zrypzfh96qlcqnt_wn7_xycr0000gn/T/tfenv_download.XXXXXX.66k3jsjd/terraform_0.11.12_darwin_amd64.zip
  inflating: /usr/local/Cellar/tfenv/2.2.3/versions/0.11.12/terraform  
Installation of terraform v0.11.12 successful. To make this your default version, run 'tfenv use 0.11.12'
(base) x@xnoMacBook-Pro terraform % tfenv use 0.11.12
Switching default version to v0.11.12
Switching completed
(base) x@xnoMacBook-Pro terraform % terraform init            

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Error installing provider "google": openpgp: signature made by unknown entity.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/darwin_amd64
```

**Comment by mobilelifeful** [comment]
error remains,

```
(base) x@xnoMacBook-Pro terraform % tfenv use 0.11.12
Switching default version to v0.11.12
Switching completed
(base) x@xnoMacBook-Pro terraform % terraform init   

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Error installing provider "google": openpgp: signature made by unknown entity.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/darwin_amd64
  ```  
   

With:

```
(base) x@xnoMacBook-Pro terraform % cat main.tf 
provider "google" {
credentials = "${var.credentials}"
region      = "${var.region}"
project     = "${var.gcp_project}"
zone        = "${var.zone}"
}

terraform {
  required_version = "0.11.12"

  required_providers {
    google = "~>2.20.2"
  }
}
```

Any more hits are appreciated.

**Comment by jshcmpbll** [comment]
@mobilelifeful sorry, at the bottom of my comment I mentioned changing the version to `2.20.3`

Is that what you have?

**Comment by mobilelifeful** [comment]
Having the same error?

**Comment by jshcmpbll** [comment]
Okay, think I figured it out..

https://github.com/hashicorp/terraform-provider-google/issues/9019#issuecomment-828732627

So I am creating a new PR to upgrade to `0.12.31`

I dont currently have GCP setup with a project.. etc. Ill push up the changes. Would you be willing to check out my working branch and test it?

**Comment by jshcmpbll** [comment]
This is the PR - https://github.com/jshcmpbll/Cloud-Mac-KVM/pull/42

Working branch is called `jc/issue-40-tf-upgrade`
